### ISSUE TITLE
Milestone 2 test cases

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/embedano#21]
Add test cases for:

- [x] transaction signing (TxId, for now, will be enough)
- [x] arbitrary data signing
- [x] proof of key ownership
