### ISSUE TITLE
Prepare to Milestone-2 acceptance

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/embedano#29]
- [x] add missing documentation (#25 )
- [x] working example of `Embedano SDK + QEMU`(#37)
- [x] review required test cases, improve if needed
